module.exports = [
 	"Androgyny",
 	"Anti-Fashion",
 	"Bogan",
 	"Bohemian",
 	"Boho-chic",
 	"Bon chic bon",
 	"Boyfriend",
 	"Business casual",
 	"Casual",
 	"Chav",
 	"Chic",
 	"Classy",
 	"Clubwear",
 	"Cool",
 	"Cycle Chic",
 	"Dress Clothes",
 	"Empire Silhouette",
 	"Flapper",
 	"Flogger",
 	"Gamine",
 	"Geek",
 	"Gibson Girl",
 	"Girlfriend",
 	"Gothic",
 	"Heroin Chic",
 	"Hipster",
 	"Ivy League",
 	"Lolita",
 	"Luxe Grunge",
 	"Madras",
 	"Preppy",
 	"Radical",
 	"Rah",
 	"Seapunk",
 	"Shabby",
 	"Size Zero",
 	"Skeet",
 	"Sloane Ranger",
 	"Soft Grunge",
 	"Swenkas",
 	"Thrift",
 	"Young Fogey"
];
